# fly.toml app configuration file for AdCP Sales Agent
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adcp-sales-agent"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.fly"

# Single unified service exposed via nginx
[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = "30s"
    grace_period = "60s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2

[env]
  PRODUCTION = "true"
  ADCP_SALES_PORT = "8080"
  ADMIN_UI_PORT = "8001"
  ADK_WEB_PORT = "8091"
  DB_TYPE = "postgresql"

[mounts]
  source = "adcp_data"
  destination = "/data"
